### ISSUE TITLE
Consider adding SPDK support

### ISSUE THREAD

**Issue by yoesmat** [kubernetes-sigs/sig-storage-local-static-provisioner#167]
There are some high performance workloads that use [SPDK](https://spdk.io/doc/about.html) over NVMe that require unloading the normal kernel driver and loading UIO/VFIO drivers for the device.

This issue is to explore allowing the workload to specify SPDK in PVC and having kubernetes storage infrastructure load the appropriate drivers and prep the device.

Similar asks:
https://github.com/kubernetes/kubernetes/issues/84085
https://github.com/spdk/spdk/issues/675

**Comment by msau42** [comment]
Right now, "device preparation" is out of scope of this project, because there are so many different ways users may want to configure their devices (raid, lvm, spdk, etc), and it will be difficult to accommodate all of them with a clean API. 

My current recommendation is to do any custom device preparation as either: 1) an init container or 2) a separate daemonset that labels nodes when its done, and have the local static provisioner only start once the node is labeled as ready.

You can see an example of 1) here: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/65
And 2) was presented in https://www.youtube.com/watch?v=eqkgiPppZN8&t=1s
