### ISSUE TITLE
Provision PV with RWX access mode

### ISSUE THREAD

**Issue by matejhasul** [kubernetes-sigs/sig-storage-local-static-provisioner#168]
Hi there,
I was wondering why provisioned PVs have hardcoded accessMode to ReadWriteOnce - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/81987abf18dab49f33e35fb658df21864a737ef5/pkg/common/common.go#L232.

I believe it makes sense to have PV which is accessed from multiple pods (running on same worker node) at the same time. Pods do not touch same data (same files) on the disk at the same time to prevent filesystem corruption but pod1 is able to hand over the work to the pod2 when pod1 is being terminated (eg. helm update) - that's why pod2 have to access the same data.

My question is why is accessMode hardcoded? Is it because there is no relevant use case for it? Or is it by design and is there any reason for it?

**Comment by cofyc** [comment]
hi, multiple pods can access a ReadWriteOnce PV on the same machine. It's easy to get wrong, please note that the [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) PV determines how PV can be mounted by nodes not by pods.

- ReadWriteOnce – the volume can be mounted as read-write by a single node
- ReadOnlyMany – the volume can be mounted read-only by many nodes
- ReadWriteMany – the volume can be mounted as read-write by many nodes

because each local PV is bound to one node, the only access mode is `ReadWriteOnce`. When a PV is attached and mounted by one node, it can be mounted into multiple pods on that node read-write or read-only (whether the volume is mounted read-only or not in the pod is determined by the `readOnly` field of `volumeMount` in the pod spec).

**Comment by matejhasul** [comment]
Thanks for quick response!

You are obviously right, it works as expected, thanks!

**Comment by backnotprop** [comment]
@cofyc do you have an example of this? Once my pv's are all assigned by the pod # that matches node total, the remaining pods fail as there are no available pv's left. Im using the latest updates and GKE / local-scsi approach.
