### ISSUE TITLE
Complete task to publish Helm chart in GitHub Pages

### ISSUE THREAD

**Issue by jamurtag** [kubernetes-sigs/sig-storage-local-static-provisioner#289]
**Is your feature request related to a problem?/Why is this needed**
[PR 280](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/280) was merged to support publication of the Helm chart via GitHub Pages, however it looks like there was a workflow error and this was not fully implemented. This issue is a request to complete that work.

**Describe the solution you'd like in detail**
Complete the work to publish the Helm chart via GitHub Pages.

**Describe alternatives you've considered**
Publishing the chart independently.

**Additional context**

**Comment by stevehipwell** [comment]
This looks to be because prow hasn't been configured to not automatically protect the `gh-pages` branch; we had this issue in a number of other sigs projects. I'll open a PR in [kubernetes/test-infra](https://github.com/kubernetes/test-infra) to fix this; once that is merged a maintainer will want to clear the `gh-pages` branch and make sure it's unprotected before doing a patch release to publish the chart.

**Comment by florentio** [comment]
Hello.
This issue is still relevant. We would like to install this chart with terraform and not having it on a repo block this https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/928

Thank you.
