### ISSUE TITLE
The local provisioner use hostPath behind the scene. Is it secure ?

### ISSUE THREAD

**Issue by raphaelpoumarede** [kubernetes-sigs/sig-storage-local-static-provisioner#319]
When looking closely at the code, I noticed that "hostPath" volume type was used (for example in this manifest : https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/local/local-pv-provisioner-nvmedisk.yaml).

The official Kubernetes [documentation ](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) discourages the usage of the  hostPath volume type because of the security risk. See the big Warning.
Do you know if the security warning and risks only applies for direct "hostPath" from the pod or if it also applies when we use the local provisioner and a PVC ? 
If yes, would it be possible to modify the provided yaml to use the ["local"](https://kubernetes.io/docs/concepts/storage/volumes/#local) volume type instead of hostPath ?
Thanks for your feedback !

**Comment by andyzhangx** [comment]
this driver is based on hostPath and finally generates `local` type volume:
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/b5987962ca8c6f53415c4ad683ddea4cb274fec6/deployment/kubernetes/example/default_example_provisioner_generated.yaml#L60-L62

**Comment by raphaelpoumarede** [comment]
Thank you Andy for your answer.
So it means that when using this local-pv-provisioner project code we are not exposed to the direct "hostPath" security risks mentioned in the Kubernetes official documentation, right?
thank you

**Comment by andyzhangx** [comment]
@raphaelpoumarede local-pv-provisioner project are using `hostPath`

**Comment by mauriciopoppe** [comment]
@raphaelpoumarede I took some notes after discussing this item with our team:

- [These volumes](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/b5987962ca8c6f53415c4ad683ddea4cb274fec6/helm/generated_examples/gke.yaml#L151-L156) are the important ones, /dev might be marked as read only but /mnt/disks might need write permissions because we need to support cleaning the data behind these volumes (2 ways of cleaning up data, rm -rf all the data in the filesystem or provide a custom cleanup job) you could try setting these as read only but we haven't tested that.
- The container is already privileged (we did a blame but couldn't find if this was set for block volumes only) and therefore even after setting the volume mounts as read only we're not sure if the attack surface is reduced.
