### ISSUE TITLE
Release Helm chart for v2.5.0

### ISSUE THREAD

**Issue by stevehipwell** [kubernetes-sigs/sig-storage-local-static-provisioner#345]
**What happened**:
There isn't a chart published for v2.5.0.

**What you expected to happen**:
The GH action is reporting as successful but there is no chart.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mauriciopoppe** [comment]
I think we didn't follow some of the steps in [RELEASE ](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/RELEASE.md) too

```
An OWNER submits a PR to bump the helm chart version to a stable version
In helm/provisioner/Chart.yaml bump the version and appVersion to the next major/minor/patch version
In helm/provisioner/values.yaml bump the image version to the next major/minor/patch version
Run ./hack/update-generated.sh
Submit a PR
An OWNER runs git tag -a $VERSION and pushes the tag with git push $VERSION.
```

**Comment by mauriciopoppe** [comment]
> My main surprise here was that the action passed, that's worth investigating.

I think that it triggered because of the tag but because there were no changes in the Chart.yaml nothing happened.

>  I'd also suggest removing the requirement to keep the versions matching as that's going to make it hard to debug chart issues, but that's not the issue here. I'd be happy to open a PR to resolve this if you'd like?

Sounds good and thanks for the help, it might be possible that there are changes in the Chart that don't involve creating a release and I think that's a valid use case.

I think there are a couple of changes, first removing the tag selector from the github workflow and then bumping the version in the chart, it'd still need to be triggered on post submit in master, that's what I propose, what do you think?

**Comment by stevehipwell** [comment]
@mauriciopoppe I've created #349 to fix these issues. If you're happy with the content and the `gh-pages` branch has been manually unprotected (if required) then merging it to `master` would result in the Helm chart being released.
