### ISSUE TITLE
e2e test against multiple nodes cluster

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-local-static-provisioner#5]
Think after [single-node cluster e2e test](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/4) is done.

Travis job has following resource limitations:

- Cores: 2
- Memory: 7.5G
- Disk: < 18G
- Stdout Log Limit: 4MB
- Timeout: 2 Hours

**Comment by msau42** [comment]
We may want to consider using prow instead of travis for kubernetes e2e tests.  The advantage is that it's easier to bring up multi-node clusters because it integrates well with the GCE platform.   You can see how we configure prow for PD CSI driver [here](https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver).  There is some [prow bootstrapping logic](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/k8s-integration/main.go#L86) to reserve and configure a project.  

It also downloads and builds latest k8s, but I think we could be simpler and just use something like:
```
kubetest --extract=ci/latest --up  # Deploy the latest ci build.
kubetest --extract=ci/latest-1.5 --up  # Deploy the latest 1.5 CI build.
```

**Comment by cofyc** [comment]
Yeah, I'm going to use prow.
