### ISSUE TITLE
Should add conditional of priorityClassName

### ISSUE THREAD

**Issue by aaahrens** [kubernetes-sigs/sig-storage-local-static-provisioner#62]
so priorityClassname can only be run in the kube-system namespace. if they specify any other namespace it fails. The template should check for a conditional, or straight up remove it (which I think would be best, considering its on the chopping block for .14 and beyond). 

the offending line is here
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/helm/provisioner/templates/provisioner.yaml#L67

**Comment by msau42** [comment]
Good catch. @cofyc can you take a look?

**Comment by cofyc** [comment]
Thanks for reporting this!

Since 1.12, [daemonset controller schedules pod by default scheduler](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#scheduled-by-default-scheduler-enabled-by-default-since-1-12), it makes sense to specify priorityClass on daemonset pods. I'm going to keep but specify it in kube-system namespace only.
